### PR TITLE
I revised the UI of dnn_activation and gave some comments on how to refactor the code

### PR DESCRIPTION
**Pull request by zhenzonglei**
I think it is a good idea to decompose the analyzer.dnn_activation into three basic elemet, 1) load network, 2, load image, 3, compute activation. These three function is very basic. it will be used everywhere in dnnbrain.

### CODE REVIEW

**Comment by zhenzonglei** [comment]
dnn_pooling:
 I think  1, pooling work for layers. We just do pooling for each channel in a layer. so we don't need to specify channel of interest.  2,we need to specify the layer of interest. But if we specify the layer and mask separately,  it will have some trouble. So I suggest we just pool the layer which lsit in the poolmask hd5 file.

**Comment by zhenzonglei** [comment]
after some rethinking of  dnn_pooling, I think we can make it simple if we  just do simple pooling across all units of a channel, and don't use the channle mask.

**Comment by zhenzonglei** [comment]
Summary,  1) dnn_perf is not necessary. 2) the channel mask in dnn_pooling is not necessary.

**Comment by sunshineDrizzle** [comment]
1. 脚本文件的docstring一般放在文件开头
2. bin/dnn_activation第20/21行，不必指明是已经训练过的网络，-net选项只负责接收用户要用的DNN的名字，至于是不是训练过的由选项-notrained指定。这就要提到bin/dnn_perf中第17~19行的改动。我将选项命名为-notrained是因为想默认是提取训练过的DNN的状态，平常是不会用到这个选项的（降低命令的使用复杂度），如果用到就表示用户要对未训练过的DNN做操作。并且未训练过的DNN不需要保存到硬盘，因为它只是一个类而已。
3. metavar应该尽量简洁，单个名字中间不要有空格。更详尽的说明
4. dest的值要符合变量命名规则（将来会被用作args的属性名）
5. bin/dnn_fe中max, mean, median这一类操作该放到哪里去呢？
6. bin/dnn_perf为何能被dnn_activation替代呢？
> I think it is a good idea to decompose the analyzer.dnn_activation into three basic elemet, 1) load network, 2, load image, 3, compute activation. These three function is very basic. it will be used everywhere in dnnbrain.
I agree with you.

> after some rethinking of dnn_pooling, I think we can make it simple if we just do simple pooling across all units of a channel, and don't use the channle mask.
I also think implementing a simple pooling is enough for us at present. But if it's too simple to just pooling the whole layer to a single value. How about imitate pytorch's pooling function.

**Pull request merged**
